window.PEC_TRACKING_DATA = {
  "meta": {
    "sourceFile": "C:\\Users\\Dpard\\OneDrive\\Documentos\\DGPPCS\\BM\\Visor\\Sistema Seguimiento-PEC - 20.04.26.xlsx",
    "sheetName": "CRONOGRAMA",
    "generatedAt": "2026-04-25T20:50:34",
    "referenceDate": "2026-04-25",
    "recordCount": 80
  },
  "summary": {
    "total": 80,
    "completed": 12,
    "inProgress": 49,
    "pending": 16,
    "withoutStatus": 3,
    "critical": 17,
    "overdue": 17,
    "attention": 1
  },
  "records": [
    {
      "id": "case-001",
      "edt": "1",
      "actividad": "DS de aprobación de endeudamiento",
      "responsable": "",
      "inicio": "2026-03-07",
      "final": "2026-03-07",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 1,
      "grupo": "1",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 1 | Completado"
    },
    {
      "id": "case-002",
      "edt": "1.1",
      "actividad": "Firma del Contrato de préstamo",
      "responsable": "",
      "inicio": "2026-03-07",
      "final": "2026-03-20",
      "duracion_cal": 14,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 2,
      "grupo": "1",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 1.1 | Completado"
    },
    {
      "id": "case-003",
      "edt": "2",
      "actividad": "Cumplimiento de condiciones de efectividad del préstamo",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-06-17",
      "duracion_cal": 90,
      "dias_habiles": 64,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Rolando Carpio/ Betsabe Araindia",
      "contacto": "Banco Mundial\nKaren Leon Altuna \nCel: 923873135\nCorreo: kleonaltuna@worldbank.org",
      "nivel": 1,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 2 | Rolando Carpio/ Betsabe Araindia | En Proceso"
    },
    {
      "id": "case-004",
      "edt": "*",
      "actividad": "Plazo para cumplimiento de condiciones de efectividad",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-06-17",
      "duracion_cal": 90,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 1,
      "grupo": "*",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT * | En Proceso"
    },
    {
      "id": "case-005",
      "edt": "2.1",
      "actividad": "Aprobación de Manual de Operaciones (MOP) de la ETGP",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-06-17",
      "duracion_cal": 90,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Betsabé Araindia /Rolando Carpio",
      "contacto": "PNSU:\nJessica Milagros De la Cruz Valdez (Jefa de Unidad de Proyectos del PNSU)\nCel: 969025469\n Correo: jdelacruz@vivienda.gob.pe\n\nJoan Paolo Horna Benavente (Coordinador de la Subunidad de Estudios)\nCel: 942880583\nCorreo: jhornab@vivienda.gob.pe\n\nJeniffer Hortensia Gonzales Armas ( Encargada del Convenio 25 y PTAR Puno)\nCel: 992245687\nCorreo: jgonzalesa@vivienda.gob.pe\n\nPASLC:\nYuri Vladimir Sullon Reyes ( Coordinador de Proyectos PTAR Julio C Tello y José Galvez)\nCel: 949283490\nCorreo: ysullon@vivienda.gob.pe\n\nEdison Joe Salvatierra Trinidad ( Especialista de Proyecto)\nCel:988898685\nCorreo: esalvatierra@vivienda.gob.pe",
      "nivel": 2,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 2.1 | Betsabé Araindia /Rolando Carpio | En Proceso"
    },
    {
      "id": "case-006",
      "edt": "2.1.1",
      "actividad": "Revisión y culminación de versión inicial del MOP",
      "responsable": "DGPPCS",
      "inicio": "2026-03-20",
      "final": "2026-04-16",
      "duracion_cal": 28,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.1.1 | DGPPCS | Completado"
    },
    {
      "id": "case-007",
      "edt": "2.1.2",
      "actividad": "Envío versión inicial del MOP al BM para revisión",
      "responsable": "BM/DGPPCS/PNSU/PASLC",
      "inicio": "2026-04-16",
      "final": "2026-04-16",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.1.2 | BM/DGPPCS/PNSU/PASLC | Completado"
    },
    {
      "id": "case-008",
      "edt": "2.1.3",
      "actividad": "Respuesta del BM a la DGPPCS",
      "responsable": "BM",
      "inicio": "2026-04-17",
      "final": "2026-04-20",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": -5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 2.1.3 | BM | En Proceso"
    },
    {
      "id": "case-009",
      "edt": "2.1.4",
      "actividad": "Revisión y culminación de versión 2 del MOP",
      "responsable": "DGPPCS",
      "inicio": "2026-04-21",
      "final": "2026-04-23",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": -2,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "vencido",
      "resumen": "EDT 2.1.4 | DGPPCS | Pendiente de Iniciar"
    },
    {
      "id": "case-010",
      "edt": "2.1.5",
      "actividad": "Envío versión 2 del MOP al BM para su no objeción",
      "responsable": "BM",
      "inicio": "2026-04-24",
      "final": "2026-04-24",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": -1,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "vencido",
      "resumen": "EDT 2.1.5 | BM | Pendiente de Iniciar"
    },
    {
      "id": "case-011",
      "edt": "2.1.6",
      "actividad": "DGPPCS remite VF-MOP a PNSU, PASLC, DGPRCS, DGAA solicitando informe técnico-legal con la opinión favorable y remisión de correo para conocimiento de la OILCC.",
      "responsable": "DGPPCS",
      "inicio": "2026-04-24",
      "final": "2026-04-27",
      "duracion_cal": 4,
      "dias_habiles": null,
      "dias_restantes": 2,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "critico",
      "resumen": "EDT 2.1.6 | DGPPCS | Pendiente de Iniciar"
    },
    {
      "id": "case-012",
      "edt": "2.1.7",
      "actividad": "DGPRCS, DGAA ,PNSU y PASLC remiten opinión favorable a DGPPCS",
      "responsable": "PNSU/PASLC",
      "inicio": "2026-04-27",
      "final": "2026-04-27",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": 2,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "critico",
      "resumen": "EDT 2.1.7 | PNSU/PASLC | Pendiente de Iniciar"
    },
    {
      "id": "case-013",
      "edt": "2.1.8",
      "actividad": "Envio de DGPPCS a VMCS para opinión",
      "responsable": "DGPPCS",
      "inicio": "2026-04-27",
      "final": "2026-04-27",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": 2,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "critico",
      "resumen": "EDT 2.1.8 | DGPPCS | Pendiente de Iniciar"
    },
    {
      "id": "case-014",
      "edt": "2.1.9",
      "actividad": "Envio de VMCS a OGPP (OI, OPM y OCAI) para opinión",
      "responsable": "VMCS",
      "inicio": "2026-04-27",
      "final": "2026-04-27",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": 2,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "critico",
      "resumen": "EDT 2.1.9 | VMCS | Pendiente de Iniciar"
    },
    {
      "id": "case-015",
      "edt": "2.1.10",
      "actividad": "Opinión de OGPP y envio a OGAJ",
      "responsable": "OGPP",
      "inicio": "2026-04-30",
      "final": "2026-05-01",
      "duracion_cal": 2,
      "dias_habiles": null,
      "dias_restantes": 6,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "critico",
      "resumen": "EDT 2.1.10 | OGPP | Pendiente de Iniciar"
    },
    {
      "id": "case-016",
      "edt": "2.1.11",
      "actividad": "Opinión de OGAJ y envío a SG",
      "responsable": "OGAJ",
      "inicio": "2026-05-01",
      "final": "2026-05-02",
      "duracion_cal": 2,
      "dias_habiles": null,
      "dias_restantes": 7,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "critico",
      "resumen": "EDT 2.1.11 | OGAJ | Pendiente de Iniciar"
    },
    {
      "id": "case-017",
      "edt": "2.1.12",
      "actividad": "SG gestiona firmas.",
      "responsable": "SG",
      "inicio": "2026-05-02",
      "final": "2026-05-02",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": 7,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "critico",
      "resumen": "EDT 2.1.12 | SG | Pendiente de Iniciar"
    },
    {
      "id": "case-018",
      "edt": "2.1.13",
      "actividad": "Publicaciòn de la RM / Portal Institucional.",
      "responsable": "SG",
      "inicio": "2026-05-03",
      "final": "2026-05-03",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 8,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "atencion",
      "resumen": "EDT 2.1.13 | SG | Pendiente de Iniciar"
    },
    {
      "id": "case-019",
      "edt": "2.2",
      "actividad": "Suscripción de convenios interinstitucionales",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-07-28",
      "duracion_cal": 131,
      "dias_habiles": null,
      "dias_restantes": 94,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Carlos Portocarrero/Fredy Ruiz",
      "contacto": "Joan Paolo Horna Benavente (Coordinador de la Subunidad de Estudios)\nCel: 942880583\nCorreo: jhornab@vivienda.gob.pe",
      "nivel": 2,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 2.2 | Carlos Portocarrero/Fredy Ruiz | En Proceso"
    },
    {
      "id": "case-020",
      "edt": "2.2.1",
      "actividad": "Convenio de cooperación Puno (PNSU)",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-07-28",
      "duracion_cal": 131,
      "dias_habiles": null,
      "dias_restantes": 94,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 2.2.1 | En Proceso"
    },
    {
      "id": "case-021",
      "edt": "2.2.1.1",
      "actividad": "Seguimiento al cierre de los proyectos zona Norte y Centro Histórico  relacionado al Convenio 25",
      "responsable": "EMSAPUNO/MPP/PNSU",
      "inicio": "2026-03-20",
      "final": "2026-06-30",
      "duracion_cal": 103,
      "dias_habiles": null,
      "dias_restantes": 66,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 2.2.1.1 | EMSAPUNO/MPP/PNSU | En Proceso"
    },
    {
      "id": "case-022",
      "edt": "2.2.1.2",
      "actividad": "Gestión del convenio con EPS EMSAPUNO , MPP y PNSU             (Por definir en negociación)",
      "responsable": "EMSAPUNO/MPP/PNSU",
      "inicio": "2026-07-03",
      "final": "2026-07-18",
      "duracion_cal": 16,
      "dias_habiles": null,
      "dias_restantes": 84,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "ok",
      "resumen": "EDT 2.2.1.2 | EMSAPUNO/MPP/PNSU | Pendiente de Iniciar"
    },
    {
      "id": "case-023",
      "edt": "2.2.1.3",
      "actividad": "Revisión y conformidad de Unidad de Asesoria Legal(UAL)  a proyecto de convenio",
      "responsable": "PNSU",
      "inicio": "2026-07-19",
      "final": "2026-07-22",
      "duracion_cal": 4,
      "dias_habiles": null,
      "dias_restantes": 88,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "ok",
      "resumen": "EDT 2.2.1.3 | PNSU | Pendiente de Iniciar"
    },
    {
      "id": "case-024",
      "edt": "2.2.1.4",
      "actividad": "Solicitud de no objeción del BM  a proyecto de convenio",
      "responsable": "BM",
      "inicio": "2026-07-22",
      "final": "2026-07-26",
      "duracion_cal": 5,
      "dias_habiles": null,
      "dias_restantes": 92,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "ok",
      "resumen": "EDT 2.2.1.4 | BM | Pendiente de Iniciar"
    },
    {
      "id": "case-025",
      "edt": "2.2.1.5",
      "actividad": "Suscripción del convenio ( MPP suscribe previa autorización de una sesión de concejo, EPS  será autorizado previa sesión del directorio)",
      "responsable": "PNSU",
      "inicio": "2026-07-27",
      "final": "2026-07-28",
      "duracion_cal": 2,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.2.1.5 | PNSU | Completado"
    },
    {
      "id": "case-026",
      "edt": "2.2.2",
      "actividad": "Convenio Lima (PASLC)",
      "responsable": "PASLC",
      "inicio": "2026-03-20",
      "final": "2026-07-28",
      "duracion_cal": 131,
      "dias_habiles": null,
      "dias_restantes": 94,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 2.2.2 | PASLC | En Proceso"
    },
    {
      "id": "case-027",
      "edt": "2.2.2.1",
      "actividad": "Desarrollo estimado (Pendiente de confirmación  PASLC)",
      "responsable": "PASCL",
      "inicio": "2026-03-20",
      "final": "2026-05-20",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 25,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "YURI SULLON (Coordinador de la Unidad de Inversiones) Cel: 949283490     PouL Huamani (Asesor de DE PASLC) Cel: 977162409",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 2.2.2.1 | PASCL | En Proceso"
    },
    {
      "id": "case-028",
      "edt": "2.3",
      "actividad": "Conformación equipo transitorio - PNSU / PASLC",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 2,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "sin_fecha",
      "resumen": "EDT 2.3 | En Proceso"
    },
    {
      "id": "case-029",
      "edt": "2.3.1",
      "actividad": "Publlicación de la RD de conformación del equipo transitorio PNSU",
      "responsable": "",
      "inicio": "2026-04-13",
      "final": "2026-04-13",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.3.1 | Completado"
    },
    {
      "id": "case-030",
      "edt": "2.3.2",
      "actividad": "No objeción a la RD de conformación del equipo transitorio PNSU",
      "responsable": "",
      "inicio": "2026-04-14",
      "final": "2026-04-24",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": -1,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 2.3.2 | En Proceso"
    },
    {
      "id": "case-031",
      "edt": "2.3.3",
      "actividad": "Seguimiento a la conformación del equipo PASLC",
      "responsable": "",
      "inicio": "2026-04-13",
      "final": "2026-04-23",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": -2,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "PouL Huamani (Asesor de DE PASLC) Cel: 977162409",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 2.3.3 | En Proceso"
    },
    {
      "id": "case-032",
      "edt": "2.3.4",
      "actividad": "Publlicación de la RD de conformación del equipo transitorio PASLC",
      "responsable": "",
      "inicio": "2026-04-13",
      "final": "2026-04-23",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": -2,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 2.3.4 | En Proceso"
    },
    {
      "id": "case-033",
      "edt": "2.3.5",
      "actividad": "No objeción a la RD de conformación del equipo transitorio PASLC",
      "responsable": "",
      "inicio": "2026-04-13",
      "final": "2026-04-23",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": -2,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 0,
      "alerta": "vencido",
      "resumen": "EDT 2.3.5 | Pendiente de Iniciar"
    },
    {
      "id": "case-034",
      "edt": "2.4",
      "actividad": "Conformación equipo clave",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-04-30",
      "duracion_cal": 42,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Betsabé Araindia/Rolando Carpio",
      "contacto": "Joan Paolo Horna Benavente (Coordinador de la Subunidad de Estudios)\nCel: 942880583\nCorreo: jhornab@vivienda.gob.pe",
      "nivel": 2,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 2.4 | Betsabé Araindia/Rolando Carpio | En Proceso"
    },
    {
      "id": "case-035",
      "edt": "2.3.1",
      "actividad": "Conformación EIP- Puno (PNSU)",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-04-30",
      "duracion_cal": 42,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 2.3.1 | En Proceso"
    },
    {
      "id": "case-036",
      "edt": "2.3.1.1",
      "actividad": "Propuesta de conformación equipo clave para efectividad (incluyendo coordinaciones internas con el BM)",
      "responsable": "PNSU/BM",
      "inicio": "2026-03-20",
      "final": "2026-04-10",
      "duracion_cal": 22,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.3.1.1 | PNSU/BM | Completado"
    },
    {
      "id": "case-037",
      "edt": "2.3.1.2",
      "actividad": "Solicitud de no objeción del BM",
      "responsable": "PNSU-DGPPCS",
      "inicio": "2026-04-10",
      "final": "2026-04-15",
      "duracion_cal": 6,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.3.1.2 | PNSU-DGPPCS | Completado"
    },
    {
      "id": "case-038",
      "edt": "2.3.1.3",
      "actividad": "No objeción del BM en forma y contenido satisfactorio",
      "responsable": "BM",
      "inicio": "2026-04-15",
      "final": "2026-04-15",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.3.1.3 | BM | Completado"
    },
    {
      "id": "case-039",
      "edt": "2.3.1.4",
      "actividad": "RD de conformación de equipo y RD de funciones",
      "responsable": "PNSU",
      "inicio": "2026-04-15",
      "final": "2026-04-30",
      "duracion_cal": 16,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 2.3.1.4 | PNSU | En Proceso"
    },
    {
      "id": "case-040",
      "edt": "2.3.2",
      "actividad": "Conformación EIP-Lima (PASLC)",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-04-30",
      "duracion_cal": 42,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 2.3.2 | En Proceso"
    },
    {
      "id": "case-041",
      "edt": "2.3.2.1",
      "actividad": "Propuesta de conformación equipo clave para efectividad",
      "responsable": "PASLC",
      "inicio": "2026-03-20",
      "final": "2026-04-10",
      "duracion_cal": 22,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.3.2.1 | PASLC | Completado"
    },
    {
      "id": "case-042",
      "edt": "2.3.2.2",
      "actividad": "Solicitud de no objeción del BM",
      "responsable": "PASLC-DGPPCS",
      "inicio": "2026-04-10",
      "final": "2026-04-15",
      "duracion_cal": 6,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.3.2.2 | PASLC-DGPPCS | Completado"
    },
    {
      "id": "case-043",
      "edt": "2.3.2.3",
      "actividad": "No objeción del BM en forma y contenido satisfactorio",
      "responsable": "BM",
      "inicio": "2026-04-15",
      "final": "2026-04-15",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Completado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 100,
      "alerta": "ok",
      "resumen": "EDT 2.3.2.3 | BM | Completado"
    },
    {
      "id": "case-044",
      "edt": "2.3.2.4",
      "actividad": "RD de conformación de equipo y RD de funciones",
      "responsable": "PASLC",
      "inicio": "2026-04-15",
      "final": "2026-04-30",
      "duracion_cal": 16,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 2.3.2.4 | PASLC | En Proceso"
    },
    {
      "id": "case-045",
      "edt": "2.3.3",
      "actividad": "Conformación Equipo ETGP- (DGPPCS)",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-04-21",
      "duracion_cal": 33,
      "dias_habiles": null,
      "dias_restantes": -4,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 2.3.3 | En Proceso"
    },
    {
      "id": "case-046",
      "edt": "2.3.3.1",
      "actividad": "Propuesta de conformación equipo clave para efectividad (un especialista de seguimiento y monitoreo) se considera coordinaciones internas con el BM",
      "responsable": "DGPPCS",
      "inicio": "2026-03-20",
      "final": "2026-04-10",
      "duracion_cal": 22,
      "dias_habiles": null,
      "dias_restantes": -15,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 2.3.3.1 | DGPPCS | En Proceso"
    },
    {
      "id": "case-047",
      "edt": "2.3.3.2",
      "actividad": "Solicitud de no objeción del BM",
      "responsable": "DGPPCS",
      "inicio": "2026-04-11",
      "final": "2026-04-17",
      "duracion_cal": 7,
      "dias_habiles": null,
      "dias_restantes": -8,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 2.3.3.2 | DGPPCS | En Proceso"
    },
    {
      "id": "case-048",
      "edt": "2.3.3.3",
      "actividad": "No objeción del BM  en forma y contenido satisfactorio",
      "responsable": "BM",
      "inicio": "2026-04-17",
      "final": "2026-04-21",
      "duracion_cal": 5,
      "dias_habiles": null,
      "dias_restantes": -4,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 4,
      "grupo": "2",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 2.3.3.3 | BM | En Proceso"
    },
    {
      "id": "case-049",
      "edt": "3",
      "actividad": "Otras Condiciones Solicitadas por el BM",
      "responsable": "",
      "inicio": "2026-03-20",
      "final": "2026-06-17",
      "duracion_cal": 90,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "Sin estado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 1,
      "grupo": "3",
      "avance_estimado": 15,
      "alerta": "ok",
      "resumen": "EDT 3 | Sin estado"
    },
    {
      "id": "case-050",
      "edt": "3.1",
      "actividad": "Evaluación de la Intervención en las Lagunas de la PTAR Espinar (CUI 2283110)",
      "responsable": "",
      "inicio": "2026-04-13",
      "final": "2026-04-22",
      "duracion_cal": 10,
      "dias_habiles": null,
      "dias_restantes": -3,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Teresa Arana",
      "contacto": "Jeniffer Hortensia Gonzales Armas ( Encargada del Convenio 25 y PTAR Puno)\nCel: 992245687\nCorreo: jgonzalesa@vivienda.gob.pe",
      "nivel": 2,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 3.1 | Teresa Arana | En Proceso"
    },
    {
      "id": "case-051",
      "edt": "3.1.1",
      "actividad": "Reunión con la EPS para evaluar los avances",
      "responsable": "",
      "inicio": "2026-04-13",
      "final": "2026-04-13",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": -12,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 3.1.1 | En Proceso"
    },
    {
      "id": "case-052",
      "edt": "3.1.2",
      "actividad": "Reunión con la DGAA para evaluar el Estudio Ambiental",
      "responsable": "",
      "inicio": "2026-04-14",
      "final": "2026-04-15",
      "duracion_cal": 2,
      "dias_habiles": null,
      "dias_restantes": -10,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 3.1.2 | En Proceso"
    },
    {
      "id": "case-053",
      "edt": "3.1.3",
      "actividad": "Reunión con la Municipalidad Provincial para evaluar el saneamiento Físico Legal de los Predios.",
      "responsable": "",
      "inicio": "2026-04-15",
      "final": "2026-04-16",
      "duracion_cal": 2,
      "dias_habiles": null,
      "dias_restantes": -9,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 3.1.3 | En Proceso"
    },
    {
      "id": "case-054",
      "edt": "3.1.4",
      "actividad": "Definición si se continua o no el Contrato",
      "responsable": "",
      "inicio": "2026-04-16",
      "final": "2026-04-22",
      "duracion_cal": 7,
      "dias_habiles": null,
      "dias_restantes": -3,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 3.1.4 | En Proceso"
    },
    {
      "id": "case-055",
      "edt": "3.2",
      "actividad": "Aprobación de los Perfiles de Puesto con RD de la DGPPCS",
      "responsable": "",
      "inicio": "",
      "final": "",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "Sandra Torres",
      "contacto": "",
      "nivel": 2,
      "grupo": "3",
      "avance_estimado": 0,
      "alerta": "sin_fecha",
      "resumen": "EDT 3.2 | Sandra Torres | Pendiente de Iniciar"
    },
    {
      "id": "case-056",
      "edt": "3.2.1",
      "actividad": "Aprobación de la RD de los perfiles de puestos del PEC por la DGPPCS",
      "responsable": "",
      "inicio": "",
      "final": "",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Pendiente de Iniciar",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 0,
      "alerta": "sin_fecha",
      "resumen": "EDT 3.2.1 | Pendiente de Iniciar"
    },
    {
      "id": "case-057",
      "edt": "3.4",
      "actividad": "Seguimiento a la Donación Componente 1: Estudios y Planes",
      "responsable": "",
      "inicio": "",
      "final": "",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Betsabé Araindia",
      "contacto": "",
      "nivel": 2,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "sin_fecha",
      "resumen": "EDT 3.4 | Betsabé Araindia | En Proceso"
    },
    {
      "id": "case-058",
      "edt": "3.4.1",
      "actividad": "Contratación de Servicio de Consultoría Estudio de Evaluación Ambiental y Social Complementario del Proyecto Convenio 25, Incluyendo PTAR El Espinar",
      "responsable": "PNSU",
      "inicio": "2026-03-20",
      "final": "2026-04-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Betsabé Araindia",
      "contacto": "PNSU:\nJessica Milagros De la Cruz Valdez (Jefa de Unidad de Proyectos del PNSU)\nCel: 969025469\n Correo: jdelacruz@vivienda.gob.pe",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 3.4.1 | PNSU | Betsabé Araindia | En Proceso"
    },
    {
      "id": "case-059",
      "edt": "3.4.2",
      "actividad": "Contratación del Servicio de Consultoría:\nEstudio Integral Sobre Estrategias de Contratación, Análisis de Costo - Beneficio y sostenibilidad para el diseño, construcción y operación de PTARs en las cuencas del lago Titicaca y Lurín.",
      "responsable": "PNSU",
      "inicio": "2026-03-20",
      "final": "2026-04-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Betsabé Araindia",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 3.4.2 | PNSU | Betsabé Araindia | En Proceso"
    },
    {
      "id": "case-060",
      "edt": "3.4.3",
      "actividad": "Contratación de Servicio de Consultoría:\nDesarrollo de la estrategia comunicacional y gestión social",
      "responsable": "PNSU",
      "inicio": "2026-03-20",
      "final": "2026-04-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 3.4.3 | PNSU | En Proceso"
    },
    {
      "id": "case-061",
      "edt": "3.4.4",
      "actividad": "Contratación de Servicio de Consultoría:\nSeparación del Exp. Técnico Del Proyecto 2387679 \" Convenio 25\" - Lote N° 1- bajo Metodología BIM",
      "responsable": "PNSU",
      "inicio": "2026-03-20",
      "final": "2026-04-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Alain Sanchez",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 3.4.4 | PNSU | Alain Sanchez | En Proceso"
    },
    {
      "id": "case-062",
      "edt": "3.4.5",
      "actividad": "Contratación de Consultorías Individuales:\nServicios profesionales de ingeniería para elaboración, supervisión y asistencia técnica para la separación del Exp. Téc. Del proyecto 2387679 \"Convenio 25\" - Lote N° 1- bajo Metodología BIM",
      "responsable": "PNSU",
      "inicio": "2026-03-20",
      "final": "2026-04-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 5,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Alain Sanchez",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "critico",
      "resumen": "EDT 3.4.5 | PNSU | Alain Sanchez | En Proceso"
    },
    {
      "id": "case-063",
      "edt": "3.5",
      "actividad": "Seguimiento a la Donación Fortalecimiento de Capacidades",
      "responsable": "",
      "inicio": "",
      "final": "2026-07-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 96,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Sandra Torres",
      "contacto": "",
      "nivel": 2,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.5 | Sandra Torres | En Proceso"
    },
    {
      "id": "case-064",
      "edt": "3.5.1",
      "actividad": "Contratación de Servicio de Consultoría:\nCertificación al personal en la gestión y ejecución de contratos FIDIC (Pasantía)/ Capacitación.",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-05-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 35,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Sandra Torres / Teresa Arana",
      "contacto": "Jeniffer Hortensia Gonzales Armas ( Encargada del Convenio 25 y PTAR Puno)\nCel: 992245687\nCorreo: jgonzalesa@vivienda.gob.pe",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.5.1 | PNSU | Sandra Torres / Teresa Arana | En Proceso"
    },
    {
      "id": "case-065",
      "edt": "3.5.2",
      "actividad": "Contratación de servicio de Consultoría\nFortalecimiento en Gestión Social y Comunicacional.",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-05-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 35,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.5.2 | PNSU | En Proceso"
    },
    {
      "id": "case-066",
      "edt": "3.5.3",
      "actividad": "Contratación de servicio de Consultoría:\nAdopción de modelos de EC en los servicios de agua y saneamiento, incluida la integración de soluciones basadas en la naturaleza.",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-05-30",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 35,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.5.3 | PNSU | En Proceso"
    },
    {
      "id": "case-067",
      "edt": "3.6",
      "actividad": "Gestión de la Donación",
      "responsable": "",
      "inicio": "",
      "final": "",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Freddy Ruiz",
      "contacto": "",
      "nivel": 2,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "sin_fecha",
      "resumen": "EDT 3.6 | Freddy Ruiz | En Proceso"
    },
    {
      "id": "case-068",
      "edt": "3.6.1",
      "actividad": "Cubrir las necesidades operativas ecenciales, incluida la adquisición de equipos básicos  los gastos administrativos y logísticos.",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Freddy Ruiz / Marjorie Mellet",
      "contacto": "Jeniffer Hortensia Gonzales Armas ( Encargada del Convenio 25 y PTAR Puno)\nCel: 992245687\nCorreo: jgonzalesa@vivienda.gob.pe",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.1 | PNSU | Freddy Ruiz / Marjorie Mellet | En Proceso"
    },
    {
      "id": "case-069",
      "edt": "3.6.2",
      "actividad": "Servicio Profesional para asistencia - profesional ambiental II",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.2 | PNSU | En Proceso"
    },
    {
      "id": "case-070",
      "edt": "3.6.3",
      "actividad": "Servicio Profesional social II para la Elaboración, gestión, monitoreo y Asistencia en la implementación de la Consultoría",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.3 | PNSU | En Proceso"
    },
    {
      "id": "case-071",
      "edt": "3.6.4",
      "actividad": "Servicio profesional de especialista en adquisiciones",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.4 | PNSU | En Proceso"
    },
    {
      "id": "case-072",
      "edt": "3.6.5",
      "actividad": "Servicio profesional de especialista financiero",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.5 | PNSU | En Proceso"
    },
    {
      "id": "case-073",
      "edt": "3.6.6",
      "actividad": "Servicio Profesional de especialista en adquisiciones - PASLC",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.6 | PNSU | En Proceso"
    },
    {
      "id": "case-074",
      "edt": "3.6.7",
      "actividad": "Servicio Profesional de especialista financiero - PASLC",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.7 | PNSU | En Proceso"
    },
    {
      "id": "case-075",
      "edt": "3.6.8",
      "actividad": "Logística para desarrollo del servicio ( Monitoreo de la Implementación de las actividades: viáticos y pasajes)",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.8 | PNSU | En Proceso"
    },
    {
      "id": "case-076",
      "edt": "3.6.9",
      "actividad": "Auditoría externa para garantizar la transparencia y la rendición de cuentas",
      "responsable": "PNSU",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 3,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.6.9 | PNSU | En Proceso"
    },
    {
      "id": "case-077",
      "edt": "3.7",
      "actividad": "Evaluación de los TdR del Head Hunter",
      "responsable": "PNSU DGPPCS",
      "inicio": "2026-04-04",
      "final": "2026-06-17",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Marjorie Mellet",
      "contacto": "Joan Paolo Horna Benavente (Coordinador de la Subunidad de Estudios)\nCel: 942880583\nCorreo: jhornab@vivienda.gob.pe",
      "nivel": 2,
      "grupo": "3",
      "avance_estimado": 55,
      "alerta": "ok",
      "resumen": "EDT 3.7 | PNSU DGPPCS | Marjorie Mellet | En Proceso"
    },
    {
      "id": "case-078",
      "edt": "4",
      "actividad": "Elaboración del Sistema de Seguimiento",
      "responsable": "",
      "inicio": "2026-04-06",
      "final": "2026-04-10",
      "duracion_cal": 5,
      "dias_habiles": null,
      "dias_restantes": -15,
      "estado": "En Proceso",
      "seguimiento_dgppcs": "Alain Sanchez",
      "contacto": "",
      "nivel": 1,
      "grupo": "4",
      "avance_estimado": 55,
      "alerta": "vencido",
      "resumen": "EDT 4 | Alain Sanchez | En Proceso"
    },
    {
      "id": "case-079",
      "edt": "",
      "actividad": "INICIO DE EFECTIVIDAD DEL PRÉSTAMO",
      "responsable": "",
      "inicio": "2026-06-17",
      "final": "2026-06-17",
      "duracion_cal": 1,
      "dias_habiles": null,
      "dias_restantes": 53,
      "estado": "Sin estado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 0,
      "grupo": "Sin grupo",
      "avance_estimado": 15,
      "alerta": "ok",
      "resumen": "Sin estado"
    },
    {
      "id": "case-080",
      "edt": "*",
      "actividad": "Sandra Torres es considerada en Lugar de Rolando Carpio (Hasta que vuelva de vacaciones)",
      "responsable": "",
      "inicio": "",
      "final": "",
      "duracion_cal": null,
      "dias_habiles": null,
      "dias_restantes": null,
      "estado": "Sin estado",
      "seguimiento_dgppcs": "",
      "contacto": "",
      "nivel": 1,
      "grupo": "*",
      "avance_estimado": 15,
      "alerta": "sin_fecha",
      "resumen": "EDT * | Sin estado"
    }
  ]
};
